### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Vexatos** [oitsjustjose/MysticMods#2]
I would like if this mod supported localizations; if it did, I am sure some people (including me) would come around to translate this nice mod.

**Comment by oitsjustjose** [comment]
It's been on my list of things I need to do, I'll start working on it soon, I've been busy lately though, so it may be a few days.

**Comment by Vexatos** [comment]
I'll wait for it.

**Comment by oitsjustjose** [comment]
Localization has been implemented, looking forward to your German translations!
