### ISSUE TITLE
[Bug] Client Crashing when Rendering Berries

### ISSUE THREAD

**Issue by Kraise** [oitsjustjose/MysticMods#7]
Client crashing with an ArrayIndexOutOfBoundsException when rendering berries in inventory. This is due to damage values being clamped to FRUIT_TYPES.length when finding the icon to load, which allows values 1 higher than the highest index of the array. I'll submit a fix for this soon.

[Crash report](https://gist.github.com/Kraise/2faa04ca22515a808950cc14110e5813)

**Comment by oitsjustjose** [comment]
Wow, didn't realize people were still doing anything with this - I thought this project had been dead for a while ;)
